### ISSUE TITLE
Is this actually stable?

### ISSUE THREAD

**Issue by SamMousa** [proj4php/proj4php#32]
This package has stable releases, but as far as I can tell there are lots of errors in the source code.
(Like missing properties on object, init functions never getting called)
Is this stable or should I think of it as more of an unstable 0.x version?

Also how can I help to make it more stable?
Many things are clearly up for improvement (changing from how JS does things to how PHP does them), but is there something with clear bounds that I could assist with?

**Comment by julien2512** [comment]
Hi SamMousa,

Proj4Php is stable for a lot of uses, but, yes, there will ever need a little more work.

Feel free to make your own fork.
As the unit test do not break, any pull request will be accepted.
If we really need to, I can create a specific branch for you.

As an example, @nickolanack starts deep unit tests to check the wgs and inline parsers.
But Proj4php still need full unit test as Proj4js do (they got sample coord for each projection !).
A good start if your using proj4php, is to add a simple unit test for your own cases (especially if you got an exotic projection).

@judgej also got a heavy road map for Proj4php. We can talk about it, because my feeling is it need a light first step.

**Comment by SamMousa** [comment]
Hi @julien2512 i'm sorry I've checked the source code for me it needs too much work to be a viable basis!

Good luck with the project!
