### ISSUE TITLE
Is grid transformation supported?

### ISSUE THREAD

**Issue by surf9** [proj4php/proj4php#52]
Hi there

I am just wondering if grid transformation is supported in Proj4PHP?

E.g. using the following projection with the nadgrids parameter and the nzgd2kgrid0005.gsb file:

`+proj=nzmg +lat_0=-41.0000000000 +lon_0=173.0000000000 +x_0=2510000.0000000000 +y_0=6023150.0000000000 +a=6378388 +rf=297 +no_defs +nadgrids=nzgd2kgrid0005.gsb`

Thanks,

**Comment by julien2512** [comment]
Proj4php was build upon Proj4js, so the answer is the same as @ahocevar !

For now, the datum_transform method in proj4php.php will be :

> ERROR: Grid shift transformations are not implemented yet.

Eventhough, if you need to implement it yourself, grid shift is described in proj4 as is :

- pj_gridlist_from_nadgrids  method (https://github.com/OSGeo/proj.4/blob/b62139be2b5f31d23bbdfa01fb2601270fc7f5b5/src/pj_gridlist.c)
- pj_apply_vgridshift method (https://github.com/OSGeo/proj.4/blob/b62139be2b5f31d23bbdfa01fb2601270fc7f5b5/src/pj_apply_vgridshift.c)
- pj_transform method  (https://github.com/OSGeo/proj.4/blob/7e2254310615a2830e1ecfd5d7538227b01d5657/src/pj_transform.c)
It seems to be applied to geoidgrids parameter only, but as the method call is "pj_gridlist_from_nadgrids" I guess this is the same.

It's a hard work.

Note we got the project to align proj4php with proj4, so that this option will be in the future (can't tell you when by now).

**Comment by surf9** [comment]
Thanks for the info.
